server:
  port: 28081
spring:
  application:
    name: rocketmq-produce-example
  cloud:
    stream:
      bindings:
        output1: { destination: test-topic, content-type: application/json }
        output2: { destination: TransactionTopic, content-type: application/json }
        output3: { destination: pull-topic, content-type: text/plain }
      rocketmq:
        binder:
          name-server: http://10.16.190.129:9876
        bindings:
          output1:
            producer:
              group: binder-group
              sync: true
          output2:
            producer:
              group: myTxProducerGroup
              producerType: Trans
              transactionListener: myTransactionListener
          output3:
            producer:
              group: pull-binder-group

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    com:
      alibaba:
        cloud:
          stream:
            binder:
              rocketmq: DEBUG